services:
  catalogo-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8227:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - UNSPLASH_API_KEY=${UNSPLASH_API_KEY}
    networks:
      - rede-cutelaria
    restart: always

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - rede-cutelaria
    restart: always

  redis:
    image: redis:alpine
    networks:
      - rede-cutelaria
    restart: always

  log-service:
    build:
      context: ./LogService
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - rede-cutelaria
    restart: always

networks:
  rede-cutelaria:
    driver: bridge